
dist: trusty
sudo: required
language: cpp

script:
 - (CXXFLAGS=-O3 scons -k)

matrix:
  include:
   # works on Precise and Trusty
   - os: linux
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-8
     install:
     env:
       - MATRIX_EVAL="CC=gcc-7 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"
