
dist: trusty
sudo: required
language: cpp

script:
 - (scons -k)

matrix:
  include:
    - compiler: gcc
      env: CXX=g++-6 CXXFLAGS="-O3"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      install:
        - sudo pip install colorama
        - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
