
dist: bionic
sudo: required
language: cpp

script:
 - (CXXFLAGS=-O3 scons -k)

matrix:
  include:
   - os: linux
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-8
     install:
     env:
       - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
    - sudo apt-get install scons
    - sudo apt-get install g++-8
    - eval "${MATRIX_EVAL}"
