// -*- mode: c++; coding: utf-8 -*-
/// @file ra.H
/// @brief Common header.

// (c) Daniel Llorens - 2019
// This library is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 3 of the License, or (at your option) any
// later version.

// FIXME ra/operators.H brings in ra/global.H and ra/complex.H, and ideally those should be separate.
// ra/bench.H and ra/test.H are also not included here.

#pragma once
#include "ra/format.H"
#include "ra/operators.H"
#include "ra/io.H"
